version: "3.4"

services:
  sde:
    image: yahu.io/sde:latest
    build: ./sde/
    volumes:
      - ws:/home/yahu/ws
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  ws:
    driver: lebokus/bindfs:latest
    driver_opts:
      sourcePath: "${SDE_WS}"
      map: "${UID:-1000}/1000:@${GID:-1000}/@1000"
